// Get Products
// Refresh Store
export const REFRESH_STORE = "REFRESH_STORE";

export const userTypes = {
	SET_USER_FORM: "SET_USER_FORM",
	SET_USER: "SET_USER",
	USER_LOCATION: "USER_LOCATION",
	SET_USER_ADDRESSES: "SET_USER_ADDRESSES",
	REMOVE_USER: "REMOVE_USER",
	SET_LOGIN_DATA: "SET_LOGIN_DATA",
};

export const authTypes = {
	SUCCESS_LOGIN: "SUCCESS_LOGIN",
	SUCCESS_SIGNUP: "SUCCESS_SIGNUP",
};

